"""initial migration 

Revision ID: 5946235501e1
Revises: 
Create Date: 2018-04-14 09:59:28.558461

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5946235501e1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('m')
    op.drop_table('girl')
    op.drop_table('user')
    op.drop_table('category')
    op.drop_table('result')
    op.drop_table('mian')
    op.drop_table('goods')
    op.drop_table('a')
    op.drop_table('t')
    op.drop_table('b')
    op.drop_table('boy')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('boy',
    sa.Column('hid', mysql.CHAR(length=1), nullable=True),
    sa.Column('bname', mysql.VARCHAR(length=20), nullable=True),
    mysql_default_charset='utf8',
    mysql_engine='MyISAM'
    )
    op.create_table('b',
    sa.Column('id', mysql.CHAR(length=1), nullable=True),
    sa.Column('num', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    mysql_default_charset='utf8',
    mysql_engine='MyISAM'
    )
    op.create_table('t',
    sa.Column('tid', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('tname', mysql.VARCHAR(length=20), nullable=True),
    mysql_default_charset='utf8',
    mysql_engine='MyISAM'
    )
    op.create_table('a',
    sa.Column('id', mysql.CHAR(length=1), nullable=True),
    sa.Column('num', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    mysql_default_charset='utf8',
    mysql_engine='MyISAM'
    )
    op.create_table('goods',
    sa.Column('goods_id', mysql.MEDIUMINT(display_width=8, unsigned=True), nullable=False),
    sa.Column('goods_name', mysql.VARCHAR(length=120), server_default=sa.text("''"), nullable=False),
    sa.Column('cat_id', mysql.SMALLINT(display_width=5, unsigned=True), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('brand_id', mysql.SMALLINT(display_width=5, unsigned=True), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('goods_sn', mysql.CHAR(length=15), server_default=sa.text("''"), nullable=False),
    sa.Column('goods_number', mysql.SMALLINT(display_width=5, unsigned=True), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('shop_price', mysql.DECIMAL(unsigned=True, precision=10, scale=2), server_default=sa.text("'0.00'"), nullable=False),
    sa.Column('market_price', mysql.DECIMAL(unsigned=True, precision=10, scale=2), server_default=sa.text("'0.00'"), nullable=False),
    sa.Column('click_count', mysql.INTEGER(display_width=10, unsigned=True), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('goods_id'),
    mysql_default_charset='utf8',
    mysql_engine='MyISAM'
    )
    op.create_table('mian',
    sa.Column('num', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    mysql_default_charset='utf8',
    mysql_engine='MyISAM'
    )
    op.create_table('result',
    sa.Column('name', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('subject', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('score', mysql.TINYINT(display_width=4), autoincrement=False, nullable=True),
    mysql_default_charset='utf8',
    mysql_engine='MyISAM'
    )
    op.create_table('category',
    sa.Column('cat_id', mysql.SMALLINT(display_width=5, unsigned=True), nullable=False),
    sa.Column('cat_name', mysql.VARCHAR(length=90), server_default=sa.text("''"), nullable=False),
    sa.Column('parent_id', mysql.SMALLINT(display_width=5, unsigned=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('cat_id'),
    mysql_default_charset='utf8',
    mysql_engine='MyISAM'
    )
    op.create_table('user',
    sa.Column('uid', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=20), server_default=sa.text("''"), nullable=False),
    sa.Column('age', mysql.SMALLINT(display_width=5, unsigned=True), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('uid'),
    mysql_default_charset='utf8',
    mysql_engine='MyISAM'
    )
    op.create_table('girl',
    sa.Column('hid', mysql.CHAR(length=1), nullable=True),
    sa.Column('gname', mysql.VARCHAR(length=20), nullable=True),
    mysql_default_charset='utf8',
    mysql_engine='MyISAM'
    )
    op.create_table('m',
    sa.Column('mid', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('hid', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('gid', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('mres', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('matime', sa.DATE(), nullable=True),
    mysql_default_charset='utf8',
    mysql_engine='MyISAM'
    )
    # ### end Alembic commands ###
